version: "3.2"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000" 
    volumes:
      - sonarq_data:/opt/sonarqube/data
      - sonarq_logs:/opt/sonarqube/logs
      - sonarq_extensions:/opt/sonarqube/extensions
    networks:
      - jenkins_sonarq

  jenkins:
    container_name: jenkins
    privileged: true
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_sonarq

networks:
      jenkins_sonarq:
        
volumes:
  jenkins_home:
  sonarq_data:
  sonarq_logs:
  sonarq_extensions: