version: '3'
services:
    app-ng:
        container_name: app-ng
        build: .
        ports:
            - "80:80"
        tty: true
        expose:
            - "80" 
        stdin_open: true
        environment:
            - MODE=prod